version: '3'

services:
  peatio:
    build:
      context: ../app/peatio
    depends_on:
      - db
      - redis
      - rabbitmq
      - smtp_relay
      - peatio_daemons
      - barong
    ports:
      - "8000:8000"
    env_file:
      - ../config/peatio.env
    volumes:
      - ../config/peatio:/opt/peatio/config:ro

  peatio_daemons:
    build:
      context: ../app/peatio
    depends_on:
      - db
      - redis
      - rabbitmq
      - coinhub
    ports:
      - "8080:8080"
    env_file:
      - ../config/peatio.env
    volumes:
      - ../config/peatio:/opt/peatio/config:ro
    command: god -c lib/daemons/daemons.god -D start

  barong:
    build:
      context: ../app/barong
    depends_on:
      - db
      - vault
    ports:
      - "8001:8001"
    env_file:
      - ../config/barong.env
